

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo k8s Terraform Azure!
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
